ALTER TABLE BADCYFILES.BACNCFE ADD ENCTID VARCHAR(04)

ALTER TABLE BADCYFILES.BACNCFE ADD ENCIDN VARCHAR(15)

ALTER TABLE BADCYFILES.BACNCFE ADD ENCNOM VARCHAR(45)

ALTER TABLE BADCYFILES.BACNCFE ADD ENCPUB VARCHAR(1)

ALTER TABLE BADCYFILES.BACNCFE ADD ENCCCY VARCHAR(3)

ALTER TABLE BADCYFILES.BACNCFE ADD ENCITB NUMERIC(15,2)

ALTER TABLE BADCYFILES.BACNCFD ADD DETITB NUMERIC(15,2)
