CREATE TABLE INTRANET_NEWS (
    ID VARCHAR(45),
    TITLE VARCHAR(150),
    DETAIL VARCHAR(10000),
    IMAGE VARCHAR(100),
    TYPE CHAR(1),
    CREATED_BY VARCHAR(45),
    UPDATED_BY VARCHAR(45),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
)
