CREATE TABLE CALDATES (
    ID VARCHAR(45),
    GROUP_ID VARCHAR(45),
    TITLE VARCHAR(200),
    STARTDATE TIMESTAMP,
    ENDDATE TIMESTAMP,
    COLOR VARCHAR(7),
    BACKCOLOR VARCHAR(7),
    BORDCOLOR VARCHAR(7),
    TEXTCOLOR VARCHAR(7),
    CREATED_BY VARCHAR(45),
    UPDATED_BY VARCHAR(45),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
)
