CREATE TABLE INTRANET_EVENT_SUBSCRIPTION_ACCOMPANISTS (
    EVENT_ID VARCHAR(45),
    OWNER VARCHAR(45),
    ACCOMPANIST_ID VARCHAR(45),
    IS_SUBSCRIBE CHAR(1),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
)
