CREATE TABLE INTGALALB (
    ID VARCHAR(45),
    NAME VARCHAR(150),
    IMAGE VARCHAR(150),
    GALDATE DATE,
    IS_ACTIVE CHAR(1),
    CREATED_BY VARCHAR(45),
    UPDATED_BY VARCHAR(45),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
)
