CREATE TABLE INTCALDATE (
    ID VARCHAR(45),
    GROUP_ID VARCHAR(45),
    TITLE VARCHAR(200),
    STARTDATE DATE,
    ENDDATE DATE,
    CREATED_BY VARCHAR(45),
    UPDATED_BY VARCHAR(45),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
)
