CREATE TABLE INTRANET_VACANCIES (
    ID VARCHAR(45),
    NAME VARCHAR(150),
    DETAIL VARCHAR(10000),
    IS_ACTIVE CHAR(1),
    CREATED_BY VARCHAR(45),
    UPDATED_BY VARCHAR(45),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
)
