CREATE TABLE INTRANET_CLAIM_FORM_CONSUMPTION_TRANSACTIONS (
    ID VARCHAR(45),
    CONSUMPTION_ID VARCHAR(45),
    TRANSACTION_DATE TIMESTAMP,
    MERCHANT_NAME VARCHAR(150),
    AMOUNT DECIMAL(10,2)
)
