CREATE TABLE INTRANET_USER_ACCOMPANISTS (
    ID VARCHAR(45),
    USER VARCHAR(45),
    NAMES VARCHAR(45),
    LAST_NAMES VARCHAR(45),
    IDENTIFICATION_TYPE VARCHAR(45),
    IDENTIFICATION VARCHAR(45),
    RELATIONSHIP VARCHAR(45)
)
