CREATE TABLE INTPGESDOC (
    ID VARCHAR(45),
    PARENT_ID VARCHAR(45),
    NAME VARCHAR(150),
    USRSACCESS VARCHAR(200),
    CREATED_BY VARCHAR(45),
    UPDATED_BY VARCHAR(45),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
)
