ALTER TABLE INTRANET_NEWS ADD LINK VARCHAR(255) BEFORE CREATED_BY

ALTER TABLE INTRANET_NEWS ADD LINK_NAME VARCHAR(150) BEFORE CREATED_BY

ALTER TABLE INTRANET_NEWS ADD LINK_VIDEO VARCHAR(255) BEFORE CREATED_BY
