CREATE TABLE INTRANET_VACANCIES_APPLICANTS (
    VACANT_ID VARCHAR(45),
    USERNAME VARCHAR(45),
    NAMES VARCHAR(45),
    FILE_NAME VARCHAR(45),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
)
