CREATE TABLE INTRANET_CLAIM_AGENTS (
    ID VARCHAR(45),
    CLAIM_ID VARCHAR(45),
    LEGAL_NAME VARCHAR(150),
    IDENTIFICATION VARCHAR(45),
    RESIDENCIAL_PHONE VARCHAR(45),
    OFFICE_PHONE VARCHAR(45),
    CELL_PHONE VARCHAR(45),
    FAX_PHONE VARCHAR(45),
    MAIL VARCHAR(100),
    CREATED_BY VARCHAR(45),
    UPDATED_BY VARCHAR(45),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
)
