CREATE TABLE INTRANET_EVENT_ACCOMPANISTS (
    ID VARCHAR(45),
    OWNER VARCHAR(45),
    NAMES VARCHAR(45),
    LAST_NAMES VARCHAR(45),
    IDENTIFICATION_TYPE VARCHAR(45),
    IDENTIFICATION VARCHAR(45),
    RELATIONSHIP VARCHAR(45),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
)
