CREATE TABLE INTCALGROU (
    ID VARCHAR(45),
    NAME VARCHAR(150),
    COLOR VARCHAR(7),
    BACKCOLOR VARCHAR(7),
    BORDCOLOR VARCHAR(7),
    TEXTCOLOR VARCHAR(7),
    IS_ACTIVE CHAR(1),
    CREATED_BY VARCHAR(45),
    UPDATED_BY VARCHAR(45),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
)
