CREATE TABLE INTRANET_CT_DC (
    ID VARCHAR(45),
    TYPE VARCHAR(45), -- CT = claim_types, DC = Distrubution Channles
    DESCRIPTION VARCHAR(255),
    IS_ACTIVE CHAR(1),
    CREATED_BY VARCHAR(45),
    UPDATED_BY VARCHAR(45),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
)
