CREATE TABLE INTRANET_COCO_IDEAS (
    ID VARCHAR(45),
    NAMES VARCHAR(150),
    MAIL VARCHAR(45),
    IDEA VARCHAR(10000),
    CREATED_BY VARCHAR(45),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
)
