CREATE TABLE INTRANET_CLAIM_FORM_CONSUMPTION (
    ID VARCHAR(45),
    CLAIM_ID VARCHAR(45),
    PRINCIPAL_CARDHOLDER_NAME VARCHAR(150),
    CC_NUMBER CHAR(16),
    CARDHOLDER_CONTACT_NUMBER VARCHAR(45),
    CLAIM_ES_NAME VARCHAR(500),
    CLAIM_ES_DETAIL VARCHAR(500),
    CLAIM_ES_DETAIL_2 VARCHAR(500),
    CLAIM_EN_NAME VARCHAR(500),
    CLAIM_EN_DETAIL VARCHAR(500),
    CLAIM_EN_DETAIL_2 VARCHAR(500),
    RESPONSE_DATE DATE,

    CREATED_BY VARCHAR(45),
    CREATED_BY_NAME VARCHAR(100),
    CREATED_BY_PHONE VARCHAR(45),
    CREATED_AT TIMESTAMP,

    UPDATED_BY VARCHAR(45),
    UPDATED_BY_NAME VARCHAR(100),
    UPDATED_AT TIMESTAMP
)
