CREATE TABLE INTRANET_CLAIM_STATUSES (
    ID VARCHAR(45),
    CLAIM_ID VARCHAR(45),
    CODE VARCHAR(45),
    DESCRIPTION VARCHAR(255),
    COMMENT VARCHAR(500),

    CREATED_BY VARCHAR(45),
    CREATED_BY_NAME VARCHAR(100),
    CREATED_AT TIMESTAMP,

    UPDATED_BY VARCHAR(45),
    UPDATED_BY_NAME VARCHAR(100),
    UPDATED_AT TIMESTAMP
)
