CREATE TABLE INTRANET_CLAIM_ATTACHES (
    ID VARCHAR(45),
    CLAIM_ID VARCHAR(45),
    FILE VARCHAR(45),

    CREATED_BY VARCHAR(45),
    CREATED_BY_NAME VARCHAR(100),
    CREATED_AT TIMESTAMP,

    UPDATED_BY VARCHAR(45),
    UPDATED_BY_NAME VARCHAR(100),
    UPDATED_AT TIMESTAMP
)
