CREATE TABLE INTREQPRPA (
    ID VARCHAR(45),
    ID_PARENT VARCHAR(45),
    TYPE VARCHAR(45),
    CODE VARCHAR(45),
    NOTE VARCHAR(255),
    VERSION VARCHAR(45),
    NAME VARCHAR(45),
    IS_ACTIVE CHAR(1),
    CREATED_BY VARCHAR(45),
    UPDATED_BY VARCHAR(45),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
)
