CREATE TABLE INTRHPAYRO (
    ID VARCHAR(45),
    PAYROLDATE DATE,

    USEREMP VARCHAR(45),
    RECORDCARD VARCHAR(45),
    IDENTIFICA VARCHAR(45),
    NAME VARCHAR(100),
    POSITION VARCHAR(150),
    DEPARTMENT VARCHAR(150),
    MAIL VARCHAR(150),

    CREATED_BY VARCHAR(45),
    CREATED_AT TIMESTAMP,

    UPDATED_BY VARCHAR(45),
    UPDATED_AT TIMESTAMP
)
