RENAME TABLE INTRANET_NEWS TO INTRANEWS

RENAME TABLE INTRANET_EVENTS TO INTREVENTS
RENAME TABLE INTRANET_EVENT_SUBSCRIPTIONS TO INTREVESUB
RENAME TABLE INTRANET_EVENT_ACCOMPANISTS TO INTREVEACO
RENAME TABLE INTRANET_EVENT_SUBSCRIPTION_ACCOMPANISTS TO INTREVSUBA

RENAME TABLE INTRANET_VACANCIES TO INTRVACAN
RENAME TABLE INTRANET_VACANCIES_APPLICANTS TO INTRVACAPP

RENAME TABLE INTRANET_COCO_IDEAS TO INTRCOCOID

RENAME TABLE INTRANET_CLAIM_PARAM TO INTRCLAPAR
RENAME TABLE INTRANET_CLAIMS TO INTRCLAIMS
RENAME TABLE INTRANET_CLAIM_FORMS TO INTRCLAFOR
RENAME TABLE INTRANET_CLAIM_FORM_TRANSACTIONS TO INTRCLAFTR
RENAME TABLE INTRANET_CLAIM_STATUSES TO INTRCLASTA
RENAME TABLE INTRANET_CLAIM_ATTACHES TO INTRCLAATT
