CREATE TABLE INTMAIITC (
    ID VARCHAR(45),
    PARENT_ID VARCHAR(45),
    DIR_TYPE CHAR(1), --TDC DIRECCIONES 1 Y 2

    WAYSENDSTA VARCHAR(45),

    ITCCOUNTRC VARCHAR(45),
    ITCCOUNTRD VARCHAR(45),

    ITCREGIONC VARCHAR(45),
    ITCREGIOND VARCHAR(45),

    ITCPROVINC VARCHAR(45),
    ITCPROVIND VARCHAR(45),

    ITCCITYC VARCHAR(45),
    ITCCITYD VARCHAR(45),

    ITCMUNICIC VARCHAR(45),
    ITCMUNICID VARCHAR(45),

    ITCSECTORC VARCHAR(45),
    ITCSECTORD VARCHAR(45),

    ITCNEIGHOC VARCHAR(45),
    ITCNEIGHOD VARCHAR(45),

    ITCSTREETC VARCHAR(45),
    ITCSTREETD VARCHAR(45),

    ITCBUINAME VARCHAR(45),
    ITCBLOCK VARCHAR(45),
    ITCHOUSNUM VARCHAR(45),
    ITCKM VARCHAR(45),
    ITCINSTRE1 VARCHAR(45),
    ITCINSTRE2 VARCHAR(45),
    ITCSPEINST VARCHAR(45),
    ITCPOSZONE VARCHAR(45),
    ITCPOSMAIL VARCHAR(45),

    ITCMPHOARE VARCHAR(45),
    ITCMPHONUM VARCHAR(45),
    ITCMPHOEXT VARCHAR(45),

    ITCSPHOARE VARCHAR(45),
    ITCSPHONUM VARCHAR(45),
    ITCSPHOEXT VARCHAR(45),

    ITCMCELARE VARCHAR(45),
    ITCMCELNUM VARCHAR(45),

    ITCSCELARE VARCHAR(45),
    ITCSCELNUM VARCHAR(45),

    ITCFAXAREA VARCHAR(45),
    ITCFAXNUMB VARCHAR(45),

    ITCMAIL VARCHAR(50)
)
