CREATE TABLE INTCURETPR (
    ID VARCHAR(45),
    DENAIL_ID VARCHAR(45),
    IS_BLACK CHAR(1),
    REQNUMBER VARCHAR(45),
    CHANNEL VARCHAR(5), -- CANAL

    PRODUCTTYP VARCHAR(50), -- TIPO DE PRODUCTO
    LIMITRD DECIMAL(12,2), -- LIMITE PESOS
    LIMITUS DECIMAL(12,2), -- LIMITE DOLARES

    --DATOS PERSONALES
    NAMES VARCHAR(150),
    LAST_NAMES VARCHAR(150),
    IDENTIFICA VARCHAR(100),
    BIRTHDATE DATE,
    NATIONALIT VARCHAR(50),
    GENDER CHAR(1),

    CELULAR_1 VARCHAR(100), --
    CELULAR_2 VARCHAR(100), --
    CELULAR_3 VARCHAR(100), --

    HOUSE_1 VARCHAR(100), --
    HOUSE_2 VARCHAR(100), --
    HOUSE_3 VARCHAR(100), --

    WORK_1 VARCHAR(100), --
    WORK_2 VARCHAR(100), --
    WORK_3 VARCHAR(100), --

    OTHER_1 VARCHAR(100), --
    OTHER_2 VARCHAR(100), --
    OTHER_3 VARCHAR(100), --

    CAMPAIGN VARCHAR(100),
    COMMITTEE VARCHAR(100),
    COMMITDATE DATE,

    CREATED_BY VARCHAR(45),
    CREATENAME VARCHAR(100),
    CREATED_AT TIMESTAMP,

    UPDATED_BY VARCHAR(45),
    UPDATENAME VARCHAR(100),
    UPDATED_AT TIMESTAMP
)
