CREATE TABLE INTTRRAPDE (
    ID VARCHAR(45),
    PRO_ID VARCHAR(45),
    SEQUENCE INTEGER,
    DESCRIP VARCHAR(150),    
    IS_ACTIVE CHAR(1),
    CREATED_BY VARCHAR(45),
    UPDATED_BY VARCHAR(45),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
)
