CREATE TABLE INTREQPRAT (
    ID VARCHAR(45),
    REQ_ID VARCHAR(45),
    FILE VARCHAR(255),

    CREATED_BY VARCHAR(45),
    CREATENAME VARCHAR(100),
    CREATED_AT TIMESTAMP,

    UPDATED_BY VARCHAR(45),
    UPDATENAME VARCHAR(100),
    UPDATED_AT TIMESTAMP
)
