CREATE TABLE INTRHEMPPA (
    ID VARCHAR(45),
    TYPE VARCHAR(45),

    NAME VARCHAR(200),

    CREATED_BY VARCHAR(45),
    CREATED_AT TIMESTAMP,

    UPDATED_BY VARCHAR(45),
    UPDATED_AT TIMESTAMP
)
