CREATE TABLE INTREQPRES (
    ID VARCHAR(45),
    REQ_ID VARCHAR(45),
    STATUS VARCHAR(255),
    COMMENT VARCHAR(1000),

    CREATED_BY VARCHAR(45),
    CREATENAME VARCHAR(100),
    CREATED_AT TIMESTAMP,

    UPDATED_BY VARCHAR(45),
    UPDATENAME VARCHAR(100),
    UPDATED_AT TIMESTAMP
)
