CREATE TABLE INTEXTBUSI (
    ID VARCHAR(45),
    NAME VARCHAR(150),
    ADDRESS VARCHAR(200),
    PHONE VARCHAR(20),

    CREATED_BY VARCHAR(45),
    CREATED_AT TIMESTAMP,

    UPDATED_BY VARCHAR(45),
    UPDATED_AT TIMESTAMP
)
