CREATE TABLE INTCURETPA (
    ID VARCHAR(45),
    TYPE VARCHAR(45),

    NOTE VARCHAR(200),

    ISBLACK CHAR(1),

    CREATED_BY VARCHAR(45),
    CREATED_AT TIMESTAMP,

    UPDATED_BY VARCHAR(45),
    UPDATED_AT TIMESTAMP
)
