CREATE TABLE INTEXTUSER (
    ID VARCHAR(45),
    BUSI_ID VARCHAR(150),
    FULL_NAME VARCHAR(45),
    IDENTIFICA VARCHAR(45),
    POSITION VARCHAR(45),
    USERNAME VARCHAR(45),
    PASSWORD VARCHAR(100),

    CREATED_BY VARCHAR(45),
    CREATED_AT TIMESTAMP,

    UPDATED_BY VARCHAR(45),
    UPDATED_AT TIMESTAMP
)
