CREATE TABLE INTCURETDC (
    ID VARCHAR(45),
    REQNUMBER VARCHAR(45),
    CHANNEL VARCHAR(5), -- CANAL
    REQSTATUS VARCHAR(255), -- STATUS

    PRODUCTTYP VARCHAR(5), -- TIPO DE PRODUCTO

    --DATOS PERSONALES
    NAMES VARCHAR(150),
    LAST_NAMES VARCHAR(150),
    IDENTIFICA VARCHAR(100),
    BIRTDATE DATE,
    NATIONALIT VARCHAR(50),
    GENDER CHAR(1),
    MARISTATUS CHAR(1),

    PSTREET VARCHAR(150),
    PNUM VARCHAR(10),
    PBUILDING VARCHAR(100),
    PAPARTAMEN VARCHAR(100),
    PSECTOR VARCHAR(100),
    PCOUNTRY VARCHAR(100),
    PMAIL VARCHAR(100),
    PNEAR VARCHAR(100), --CERCA DE
    PSCHEDULE VARCHAR(100), -- HORARIO DE ENTREGA

    PNAMEPLAST VARCHAR(27), -- NOMBRE PLASTICO

    PPHONE_RES VARCHAR(100), -- RESIDENCIAL
    PPHONE_CEL VARCHAR(100), -- CELULAR

    --DATOS LABORALES
    BUSINENAME VARCHAR(100), -- NOMBRE EMPRESA
    POSITION VARCHAR(100),
    WORKINTIME VARCHAR(50), -- TIEMPO LABORANDO

    LSTREET VARCHAR(150),
    LNUM VARCHAR(10),
    LBUILDING VARCHAR(100),
    LAPARTAMEN VARCHAR(100),
    LSECTOR VARCHAR(100),
    LCOUNTRY VARCHAR(100),
    LMAIL VARCHAR(100),
    LNEAR VARCHAR(100), --CERCA DE
    LSCHEDULE VARCHAR(100), -- HORARIO DE ENTREGA

    PPHONE_OFF VARCHAR(100), -- OFICINA
    PPHONE_EXT VARCHAR(100), -- EXTENCION
    PPHONE_FAX VARCHAR(100), -- FAX

    MONTINCOME VARCHAR(100), -- INGRESOS MENSUALES
    OTHEINCOME VARCHAR(100), -- INGRESOS OTROS

    --REFERENCIAS PERSONALES
    REF1NAMES VARCHAR(100), -- NOMBRE Y APELLIDOS DE REFERENCIAS
    REF1PHORES VARCHAR(100), -- TELEFONO RESIDENCIAL
    REF1PHOCEL VARCHAR(100), -- TELEFONO CELULAR

    REF2NAMES VARCHAR(100), -- NOMBRE Y APELLIDOS DE REFERENCIAS
    REF2PHORES VARCHAR(100), -- TELEFONO RESIDENCIAL
    REF2PHOCEL VARCHAR(100), -- TELEFONO CELULAR

    CREATED_BY VARCHAR(45),
    CREATENAME VARCHAR(100),
    CREATED_AT TIMESTAMP,

    UPDATED_BY VARCHAR(45),
    UPDATENAME VARCHAR(100),
    UPDATED_AT TIMESTAMP
)
