CREATE TABLE INTRAFAQS (
    ID VARCHAR(45),
    THEME_ID VARCHAR(45),
    QUESTION VARCHAR(500),
    ANSWER VARCHAR(1000),
    IS_ACTIVE CHAR(1),
    CREATED_BY VARCHAR(45),
    UPDATED_BY VARCHAR(45),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
)
