CREATE TABLE INTREQRH (
    ID VARCHAR(45),
    REQNUMBER VARCHAR(45),
    REQTYPE VARCHAR(255), -- TIPO DE SOLICITUD
    REQSTATUS VARCHAR(255), -- STATUS
    NOTE VARCHAR(1000), -- DESCRIPCION

    COLUSER VARCHAR(45), --USUARIO
    COLCODE VARCHAR(45), --CODIGO COLABORADOR
    COLNAME VARCHAR(100), --NOMBRE COLABORADOR
    COLPOSI VARCHAR(100), --POSICION
    COLDEPART VARCHAR(100), --DEPARTAMENTO

    COLSUPUSER VARCHAR(45), --SUPERVISOR USUARIO
    COLSUPNAME VARCHAR(45), --SUPERVISOR NOMBRE
    APPROVESUP CHAR(1), --APROBADO POR SUPERVISOR

    RHUSER VARCHAR(45), --RH USUARIO
    RHNAME VARCHAR(45), --RH NOMBRE
    APPROVERH CHAR(1), --APROBADO POR RH

    CREATED_BY VARCHAR(45),
    CREATENAME VARCHAR(100),
    CREATED_AT TIMESTAMP,

    UPDATED_BY VARCHAR(45),
    UPDATENAME VARCHAR(100),
    UPDATED_AT TIMESTAMP
)
